### PR TITLE
v2.1.0

### LINKED ISSUE #8: No indication is given on transmit timeout with callback configured
After establishing a Modbus TCP connection between the Wiznet, acting as client and a peer acting as a server, if during a transmit from the client to server the connection is broken, i.e by removing the ethernet cable at the server end, no indication is given. Using Wireshark, we can see that the Wiznet attempts to re-transmit the packets and gives up after the configurable time period. Adding debug shows that the detected timeout is never propagated up to the caller who initiated the transmit. 

With further debugging we noticed that the transmit callback handler is deleted immediately when the Sn_IR (Socket n Interrupt Register) [SEND_OK] bit is set. When the timeout later occurs, although the TIMEOUT bit in the Sn_IR register is set, it then attempts to call the callback handler but it has already been deleted by the SEND_OK case.

The following code shows a workaround for the above issue. The _transmitCallback has been moved from the SEND_COMPLETE to DATA_RECEIVED case and the callback is successfully called indicating timeout.

// ***************************************************************************
// _handleSocketInt, handles/clears the specified socket interrupt
// Returns: null
// Parameters: socket the interrupt occurred on
// **************************************************************************
function handleInterrupt(skip_timer = false) {
   ...
    if (status.SEND_COMPLETE) {

        // server.log("Send complete on socket " + _socket);
        _driver.clearSocketInterrupt(_socket, W5500_SEND_COMPLETE_INT_TYPE);
        skip_timer = true;
    }

    if (status.DATA_RECEIVED) {

        // server.log("Data received on socket " + _socket);
        _driver.clearSocketInterrupt(_socket, W5500_DATA_RECEIVED_INT_TYPE);

        // At this point we know we have successfully transmited last message so we can
        // now safely remove the calling transmit callback handler
        local _transmitCallback = _getHandler("transmit");
        if (_transmitCallback) {
            _handlers["transmit"] <- null;

            imp.wakeup(0, function() {
                _transmitCallback(null);
            }.bindenv(this))
        }
        receive(); // process incoming data
    }
    ...
}

### PR DESCRIPTION
**Pull request by ppetrosh**
Introduced `setMac`, which specifies whether the library should set the MAC address of the chip to the imp's MAC.

### CODE REVIEW

**Comment by ppetrosh** [comment]
@betzrhodes do you see any issues with these changes?

**Review by betzrhodes — APPROVED** [review]
Looks good.

**Comment by smittytone** [comment]
Re. getLeaseTime() in the DHCP - is this in seconds? We should add whatever the unit is to the doc.

Also the DHCP references an init() method which is not listed in the doc and not in the class file either. I presume this should be removed?

**Comment by ppetrosh** [comment]
@smittytone yes `getLeaseTime` is in seconds. Yes, please add this into the documentation.

**Comment by ppetrosh** [comment]
@smittytone as for `init` there is no `DHCP.init()` method. Any references to it should be removed.

**Comment by chrisjbremner** [comment]
@smittytone I just realized that [this line](https://github.com/electricimp/Wiznet_5500/pull/9/commits/b055797dd60525e019ca892098e270401da24e29#diff-04c6e90faac2675aa89e2176d2eec7d8R20) is technically not correct since the MAC of the WIZ5500 is set to a [slightly modified](https://github.com/electricimp/Wiznet_5500/blob/4d9b55fa8c2512f034c26a5cd9810d7eeac0a1b0/W5500.device.lib.nut#L994-L997) version of the Imp's own MAC.

**Comment by ppetrosh** [comment]
That's a good point @chrisjbremner, thanks!

**Comment by chrisjbremner** [comment]
Should I make a branch to make these last updates?

**Comment by ppetrosh** [comment]
@chrisjbremner if you can do it on the same branch and just create a new PR that would be very helpful! Thanks!

**Comment by chrisjbremner** [comment]
Cool looks like we're all up to date. Anything else that needs to be done? What does the deploy process for a new version of a library look like?

**Comment by ppetrosh** [comment]
Thank you @chrisjbremner!

@smittytone once you approve the changes, I'll go ahead with rolling out the new library version.

**Comment by chrisjbremner** [comment]
@ppetrosh is there a way to run a branch of this package from the Electric Imp IDE while I am waiting for a new version to be deployed? I have just been copy/pasting all of the code into my device file for now which is a bit cumbersome.

**Comment by chrisjbremner** [comment]
@smittytone do you mind taking a look at this? Thanks!

**Comment by ppetrosh** [comment]
I pinged @smittytone via email separately.

**Comment by chrisjbremner** [comment]
Thanks @ppetrosh, I appreciate it!

**Review by smittytone — APPROVED** [review]

**Comment by ppetrosh** [comment]
Thank you @smittytone @chrisjbremner!

The new version is released and available via:

#require "W5500.device.lib.nut:2.1.0"

**Comment by chrisjbremner** [comment]
I tested it on my end, I was able to import the library. Thanks again @ppetrosh and @smittytone!

**Pull request merged**
